---
title: "043_PanNET_Marco_Visani"
author: "Marco Visani"
date: "2022-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
# Part 1
First load required functions 
```{r, error=FALSE}
rm(list = ls())
library(DMRcate)
library(ChAMP)
library(minfi)
library(readr)
library(base)
library(doParallel)
source("ChAMP_functions_Lionel_Philipp_220727.R")
#source("test.R")
```

# EPIC pre-process
Read the raw data.The function readRDS allows the read R Data Format: RDS
```{r}
path_epic <- "./raw_data/training_EPIC.Rds"
meth_epic.rgSet <-  readRDS(path_epic)
```

```{r}
# get detection p values
#detectionP(METH.rgSet)
#getNBeads(METH.rgSet)
```

## run NOOB 
```{r message=FALSE}
meth_epic <- champ.load_extended(rgSet_object = meth_epic.rgSet, 
                           sampleSheet = meth_epic.sampleSheet,
                           method = "minfi", 
                           filterDetP = T, # include low p value probes
                           filterBeads = T, # include probes detected in few beads
                           detPcut = 1,
                           arraytype = "EPIC", # set accorgingly
                           preproc = "Noob", 
                           dyeMethod = "single", 
                           dataToInclude = c("loadQC", "mset"),
                           ProbeCutoff = 0,
                           force = F)
rm(meth_epic.rgSet)
```

Removing legacy probes. 
```{r}
EPIC_legacy_probes <-  read_delim("P:/Forschung/GRP Perren_Marinoni/1. Group/2. People/17. Philipp Kirchner/projects/shared_data/Illumina_methylation_arrays/MethylationEPIC Missing Legacy CpG (v1.0_B3 vs. v1.0_B2).txt.gz",
                                delim = "\t",
                                show_col_types = F)

meth_epic$mset <- meth_epic$mset[!(rownames(meth_epic$mset) %in% EPIC_legacy_probes$TargetID), ]
rm(EPIC.manifest.hg19)
```

<<<<<<< HEAD
remove variables from ChAMP source file and add data to empty list
=======

## convert to beta values (meth / unmeth + meth)
shared_probes is the row names -> order them and then fuse both files
```{r}
row_names_epic <- sort(rownames(meth_epic$mset))
meth_epic.beta <- getBeta(meth_epic$mset, "Illumina")[row_names_epic, ]


rm(meth_epic, row_names_epic) #remove data that we don't need anymore... (to test)
```




# 450k pre-process
```{r}
path_450k <- "./raw_data/training_450K.Rds"
meth_450.rgSet <- readRDS(path_450k)
```

## run NOOB 
```{r, message=FALSE}
meth_450 <- champ.load_extended(rgSet_object = meth_450.rgSet, 
                           sampleSheet = meth_450.sampleSheet,
                           method = "minfi", 
                           filterDetP = T, # include low p value probes
                           filterBeads = T, # include probes detected in few beads
                           detPcut = 1,
                           arraytype = "450K", # set accorgingly
                           preproc = "Noob", 
                           dyeMethod = "single", 
                           dataToInclude = c("loadQC", "mset"),
                           ProbeCutoff = 0,
                           force = F)
rm(meth_450.rgSet)
```

remove legacy probes from 450k array
```{r}
meth_450$mset <- meth_450$mset[!(rownames(meth_450$mset) %in% EPIC_legacy_probes$TargetID), ]
```


## convert beta values for 450k sample
```{r}
row_names_450 <- sort(rownames(meth_450$mset))
meth_450.beta <- getBeta(meth_450$mset, "Illumina")[row_names_450, ]
rm(meth_450, row_names_450)
```




# Combine 450K and EPIC beta matrices (intersection)
```{r}
row_names <- intersect(rownames(meth_epic.beta), rownames(meth_450.beta))
meth.beta <- cbind(meth_450.beta[row_names, ], meth_epic.beta[row_names,])

#remove all unuseful data to free up RAM
rm(EPIC_legacy_probes, hm450.manifest.hg19, multi.hit, probe.features, row_names, meth_450.beta, meth_epic.beta)

```



# put probes in ascending order

```{r}
#free up unused memory
gc()

#detect cores for parallelism
n_cores <- detectCores()-2

#run function
meth.norm <- champ.norm(meth.beta, 
                       arraytype = "450K", 
                       cores = n_cores,
                       resultsDir = "results")
```
